---
- name: add VirtualBox apt key
  sudo: yes
  apt_key:
    url: "{{ virtualbox_download_url }}/debian/oracle_vbox.asc"
    state: present

- name: add Virtualbox repository
  sudo: yes
  apt_repository:
    repo: "deb {{ virtualbox_download_url }}/debian {{ ansible_lsb.codename }} contrib"
    state: present
    update_cache: true

- name: ensure distribution-packaged VirtualBox is not installed
  sudo: yes
  apt: 
    pkg: "{{ item }}"
    state: absent
  with_items:
    - virtualbox
    - virtualbox-dkms
    - virtualbox-qt

- name: update to latest Oracle-packaged VirtualBox 
  sudo: yes
  apt: 
    pkg: "{{item}}" 
    state: latest 
  with_items:
    - "{{ virtualbox_package_name }}"

- name: install additional VirtualBox dkms package
  sudo: yes
  apt:
    pkg: "{{virtualbox_dkms_package_name}}"
    state: present 
  when: virtualbox_dkms_enable

- name: register current VirtualBox version
  shell: VBoxManage --version | cut --delimiter=r --field=1
  register: virtualbox_version
  changed_when: false
  when: virtualbox_extension_enable

- name: register current VirtualBox build number
  shell: VBoxManage --version | cut --delimiter=r --field=2
  register: virtualbox_buildnumber
  changed_when: false
  when: virtualbox_extension_enable

- set_fact: 
    virtualbox_extension_package_name: "Oracle_VM_VirtualBox_Extension_Pack-{{ virtualbox_version.stdout }}-{{ virtualbox_buildnumber.stdout }}.vbox-extpack"
  when: virtualbox_extension_enable

- set_fact:
    virtualbox_extension_package_url : "{{ virtualbox_download_url }}/{{ virtualbox_version.stdout }}/{{ virtualbox_extension_package_name }}"
  when: virtualbox_extension_enable

- name: download VirtualBox extension pack
  get_url: url={{ virtualbox_extension_package_url }} dest=/tmp/{{ virtualbox_extension_package_name }} 
  when: virtualbox_extension_enable

  # TODO this always reports as `changed`
- name: install VirtualBox extension pack
  sudo: yes
  command: VBoxManage extpack install --replace /tmp/{{ virtualbox_extension_package_name }}
  when: virtualbox_extension_enable
